version: "3.8"

services:
  go:
    container_name: krisha-go
    build:
      context: .
      dockerfile: dockerfile/Dockerfile
    env_file:
      - .env
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    restart: on-failure
  postgres:
    image: postgres:latest
    container_name: krisha
    env_file :
      - .env
    ports:
      - "5433:5432"
    volumes:
      - krisha:/var/lib/postgresql/data
    restart: always
volumes:
  krisha:
