version: "3.8"

services:
  go:
    container_name: krisha-go
    build:
      context: .
      dockerfile: dockerfile/Dockerfile
    command:  ./
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:alpine
    container_name: db4
    env_file :
      - .env
    ports:
      - "5433:5432"
    volumes:
      - krisha_krisha:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  krisha_krisha:
