version: "3.8"

services:
  go:
    build:
      context: .
      dockerfile: dockerfile/Dockerfile
    env_file:
      - .env
    ports:
      - "8081:8081"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: db
    env_file :
      - .env
    ports:
      - "5432:5432"
    volumes:
      - krisha:/var/lib/postgresql/data
volumes:
  krisha:
